// <auto-generated />
using System;
using AttendanceApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AttendanceApi.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260828073010_AddSprint5Tables")]
    partial class AddSprint5Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AttendanceApi.Domain.Entities.AttendanceAdjustment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AdjustedCheckIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adjusted_check_in");

                    b.Property<DateTime?>("AdjustedCheckOut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adjusted_check_out");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("adjustment_type");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("integer")
                        .HasColumnName("approver_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_adjustments_status");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .HasDatabaseName("idx_adjustments_emp_date");

                    b.ToTable("attendance_adjustments", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.AttendanceDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("IpAddress");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastSyncAt");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Location");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4370)
                        .HasColumnName("Port");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ONLINE")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("attendance_devices", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.DailyAttendanceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<int>("EarlyMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("early_minutes");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("LateMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("late_minutes");

                    b.Property<decimal>("OvertimeHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("overtime_hours");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ABSENT'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.Property<decimal>("WorkHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("work_hours");

                    b.Property<int?>("WorkShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("work_shift_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_daily_records_status");

                    b.HasIndex("WorkDate")
                        .HasDatabaseName("idx_daily_records_date");

                    b.HasIndex("WorkShiftId");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .IsUnique()
                        .HasDatabaseName("uq_daily_records_emp_date");

                    b.ToTable("daily_attendance_records", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdateAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.DeviceEmployeeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("DeviceId");

                    b.Property<string>("DeviceUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DeviceUserId");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmployeeId");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("DeviceId", "DeviceUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_device_user");

                    b.ToTable("device_employee_mappings", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.DeviceSyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("RecordsInserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("records_inserted");

                    b.Property<int>("RecordsPulled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("records_pulled");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("SUCCESS")
                        .HasColumnName("status");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("AUTO_SCHEDULED")
                        .HasColumnName("sync_type");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_sync_logs_device_id");

                    b.ToTable("device_sync_logs", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EmployeeCode");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("EndDate");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("FullName");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Position");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("integer")
                        .HasColumnName("approver_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("leave_type");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.Property<decimal>("TotalDays")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("total_days");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_leave_requests_status");

                    b.HasIndex("EmployeeId", "FromDate", "ToDate")
                        .HasDatabaseName("idx_leave_requests_emp");

                    b.ToTable("leave_requests", null, t =>
                        {
                            t.HasCheckConstraint("chk_leave_dates", "to_date >= from_date");
                        });
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.MonthlyTimesheetSummary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AbsentDays")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("absent_days");

                    b.Property<decimal>("ActualWorkingDays")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("actual_working_days");

                    b.Property<decimal>("ActualWorkingHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("actual_working_hours");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EarlyMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("early_minutes");

                    b.Property<int>("EarlyOccurrences")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("early_occurrences");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<int?>("FinalizedBy")
                        .HasColumnType("integer")
                        .HasColumnName("finalized_by");

                    b.Property<int>("LateMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("late_minutes");

                    b.Property<int>("LateOccurrences")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("late_occurrences");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<decimal>("OvertimeHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("overtime_hours");

                    b.Property<decimal>("PaidLeaveDays")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("paid_leave_days");

                    b.Property<decimal>("StandardWorkingDays")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("standard_working_days");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPayableDays")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("total_payable_days");

                    b.Property<decimal>("UnpaidLeaveDays")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("unpaid_leave_days");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("FinalizedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_monthly_timesheets_status");

                    b.HasIndex("Year", "Month")
                        .HasDatabaseName("idx_monthly_timesheets_period");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("uq_monthly_timesheet_emp_period");

                    b.ToTable("monthly_timesheet_summaries", null, t =>
                        {
                            t.HasCheckConstraint("chk_timesheet_month", "month >= 1 AND month <= 12");

                            t.HasCheckConstraint("chk_timesheet_year", "year >= 2000");
                        });
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.RawAttendanceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CheckTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_user_id");

                    b.Property<string>("ProcessedStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("processed_status");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<string>("VerifyMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("FINGERPRINT")
                        .HasColumnName("verify_mode");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedStatus")
                        .HasDatabaseName("idx_raw_logs_status");

                    b.HasIndex("DeviceId", "DeviceUserId", "CheckTime")
                        .IsUnique()
                        .HasDatabaseName("uq_raw_logs_dedup");

                    b.ToTable("raw_attendance_logs", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.Property<int>("WorkShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("work_shift_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkShiftId");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .IsUnique()
                        .HasDatabaseName("idx_work_schedules_lookup");

                    b.ToTable("work_schedules", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.WorkShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("BreakEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_end_time");

                    b.Property<TimeOnly?>("BreakStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_start_time");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("GracePeriodMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("grace_period_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOvernight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_overnight");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("WorkHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(8.00m)
                        .HasColumnName("work_hours");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_work_shifts_code");

                    b.ToTable("work_shifts", (string)null);
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.AttendanceAdjustment", b =>
                {
                    b.HasOne("AttendanceApi.Domain.Entities.Employee", "Approver")
                        .WithMany("ApprovedAttendanceAdjustments")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_adjustments_approver");

                    b.HasOne("AttendanceApi.Domain.Entities.Employee", "Employee")
                        .WithMany("AttendanceAdjustments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adjustments_employee");

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.DailyAttendanceRecord", b =>
                {
                    b.HasOne("AttendanceApi.Domain.Entities.Employee", "Employee")
                        .WithMany("DailyAttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceApi.Domain.Entities.WorkShift", "WorkShift")
                        .WithMany("DailyAttendanceRecords")
                        .HasForeignKey("WorkShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.DeviceEmployeeMapping", b =>
                {
                    b.HasOne("AttendanceApi.Domain.Entities.AttendanceDevice", "AttendanceDevice")
                        .WithMany("DeviceEmployeeMappings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceApi.Domain.Entities.Employee", "Employee")
                        .WithMany("DeviceEmployeeMappings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceDevice");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.DeviceSyncLog", b =>
                {
                    b.HasOne("AttendanceApi.Domain.Entities.AttendanceDevice", "AttendanceDevice")
                        .WithMany("DeviceSyncLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_logs_device");

                    b.Navigation("AttendanceDevice");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.Employee", b =>
                {
                    b.HasOne("AttendanceApi.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("AttendanceApi.Domain.Entities.Employee", "Approver")
                        .WithMany("ApprovedLeaveRequests")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leave_requests_approver");

                    b.HasOne("AttendanceApi.Domain.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leave_requests_employee");

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.MonthlyTimesheetSummary", b =>
                {
                    b.HasOne("AttendanceApi.Domain.Entities.Employee", "Employee")
                        .WithMany("MonthlyTimesheetSummaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monthly_timesheets_employee");

                    b.HasOne("AttendanceApi.Domain.Entities.Employee", "Finalizer")
                        .WithMany("FinalizedMonthlyTimesheets")
                        .HasForeignKey("FinalizedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_monthly_timesheets_finalizer");

                    b.Navigation("Employee");

                    b.Navigation("Finalizer");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.RawAttendanceLog", b =>
                {
                    b.HasOne("AttendanceApi.Domain.Entities.AttendanceDevice", "AttendanceDevice")
                        .WithMany("RawAttendanceLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_raw_logs_device");

                    b.Navigation("AttendanceDevice");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("AttendanceApi.Domain.Entities.Employee", "Employee")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceApi.Domain.Entities.WorkShift", "WorkShift")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("WorkShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.AttendanceDevice", b =>
                {
                    b.Navigation("DeviceEmployeeMappings");

                    b.Navigation("DeviceSyncLogs");

                    b.Navigation("RawAttendanceLogs");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.Employee", b =>
                {
                    b.Navigation("ApprovedAttendanceAdjustments");

                    b.Navigation("ApprovedLeaveRequests");

                    b.Navigation("AttendanceAdjustments");

                    b.Navigation("DailyAttendanceRecords");

                    b.Navigation("DeviceEmployeeMappings");

                    b.Navigation("FinalizedMonthlyTimesheets");

                    b.Navigation("LeaveRequests");

                    b.Navigation("MonthlyTimesheetSummaries");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("AttendanceApi.Domain.Entities.WorkShift", b =>
                {
                    b.Navigation("DailyAttendanceRecords");

                    b.Navigation("WorkSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
